## 2D Example

### Create the array
Create an array that is the same shape as the array on the worksheet.

In [14]:
import numpy as np

In [3]:
# nope.
np.array([[1,5,9], [3,7,11]])

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [7]:
array = np.array([[1,3], [5,7], [9,11]])
print(array)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [6]:
array.shape

(3, 2)

When we define arrays with lists the innermost dimension is 0 (rows)

### Index the array

In [11]:
array[:,0]

array([1, 5, 9])

### Aggregations over an axis

In [12]:
array.max(axis=0)

array([ 9, 11])

In [13]:
array.max(axis=1)

array([ 3,  7, 11])

## 3D Example

### Create the array

In [18]:
array_3d = np.array([[[1,3], [5,7], [9,11]], [[2,4], [6,8], [10,12]]])
print(array_3d)

[[[ 1  3]
  [ 5  7]
  [ 9 11]]

 [[ 2  4]
  [ 6  8]
  [10 12]]]


In [20]:
array_3d[2,1]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [21]:
array_3d[0,2,1]

11

In [24]:
array_3d[0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [26]:
array_3d[0,:,0]

array([1, 5, 9])

In [28]:
array_3d.mean(axis=0)

array([[ 1.5,  3.5],
       [ 5.5,  7.5],
       [ 9.5, 11.5]])

### 📝 Checking In

Consider an array of the following form called `example_array`:

|   |   |   |  |  |
|---|---|---|---|---|
| 1  | 2  |3   | 4 | 5 |
|  6 |  7 | 8 | 9 | 10 |
| 11 | 12 | 13 | 14 | 15 |
| 16 | 17 | 18 | 19 | 20 |

1. What is the value at index [0, 2]?
1. What is the result of `example_array[4]`?
2. What is the result of `example_array[1:3, 2]`?
1. Give the index to return the value 15.